### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by vhzy** [THUNLP-MT/FIIG#1]
Great work!
I'm looking forward to following your work，I wonder how soon you expect to release the open source code？
THX!

**Comment by wangphoebe** [comment]
Hi @vhzy ,
Hopefully we will release the code this month ASAP. The implementation details, including the OpenAI API version and the prompts, are listed in our [paper](https://arxiv.org/pdf/2311.11598.pdf).  
You can also refer to the other two projects [PICa](https://github.com/microsoft/PICa) and [Prophet](https://github.com/MILVLG/prophet) for requesting OpenAI API.
If you encounter any urgent problems, feel free to send me an email.

**Comment by vhzy** [comment]
> Hi @vhzy , Hopefully we will release the code this month ASAP. The implementation details, including the OpenAI API version and the prompts, are listed in our [paper](https://arxiv.org/pdf/2311.11598.pdf). You can also refer to the other two projects [PICa](https://github.com/microsoft/PICa) and [Prophet](https://github.com/MILVLG/prophet) for requesting OpenAI API. If you encounter any urgent problems, feel free to send me an email.

Thank you for your reply!
I'm curious whether you call OpenAI's LLM interface online and then train the filter model; or you call LLM first through offline operation, then collect all the data and train the filter model?

**Comment by vhzy** [comment]
Thank you for your reply!
I'm curious whether you call OpenAI's LLM interface online and then train
the filter model; or you call LLM first through offline operation, then
collect all the data and train the filter model?
Also, the openai interface is blocked in China. How do you solve this
problem?
Finally, if I may, I am also curious about how much you spent on the API
for this article?

wangphoebe ***@***.***> 于2023年12月1日周五 14:41写道：
